jest.config.js, package.json, tests/index.test.ts
Instructed `jest` to pass when no tests are present.
N/A
As this project is brand new, let's not have the [`integration`](https://github.com/adobe/magento-storefront-event-collector/actions/workflows/integration.yml) action fail because no tests are present.
Running `npm run test` no longer fails.
=> test: pass with no tests for now

.prettierignore
Ignore `CHANGELOG.md` when running `prettier`.
N/A
The `CHANGELOG.md` file is generated by [standard-version](https://github.com/adobe/magento-storefront-events-sdk/actions/runs/665426980) and should be ignored when formatting, as it will cause `prettier` to fail.
Tested locally by running `npm run format`.
=> chore: ignore changelog in prettier

example/index.html, src/handlers/search/searchCategoryClick.ts, src/handlers/search/searchProductClick.ts, src/handlers/search/searchRequestSent.ts, src/handlers/search/searchResponseReceived.ts, src/handlers/search/searchResultsView.ts, src/handlers/search/searchSuggestionClick.ts, src/index.ts, src/schemas.ts, src/snowplow.ts
Construct Snowplow contexts from the Magento Data Layer.
[SEARCH-1105](https://jira.corp.magento.com/browse/SEARCH-1105)
Context data is required for proper data modeling in Snowflake.
Tested locally in the `example` directory with the Snowplow Chrome extension.
-   [ ] I …
=> SEARCH-1105 | construct snowplow contexts from data layer

example/index.html, src/contexts/index.ts, src/contexts/search/index.ts, src/contexts/tracker.ts, src/handlers/search/searchCategoryClick.ts, src/handlers/search/searchProductClick.ts, src/handlers/search/searchRequestSent.ts, src/handlers/search/searchResponseReceived.ts, src/handlers/search/searchResultsView.ts, src/handlers/search/searchSuggestionClick.ts, src/index.ts, src/schemas.ts, src/snowplow.ts, tsconfig.json
Create the `magentoJsTracker` context and include it with global contexts.
[SEARCH-1161](https://jira.corp.magento.com/browse/SEARCH-1161)
We need to support all global contexts that our previous tracker does.
Tested locally with the `example` directory, monitoring events with the Snowplow Chrome extension and Kibana.
- …
=> SEARCH-1161 | create magento js tracker context

example/index.html, src/contexts/index.ts, src/contexts/search/index.ts, src/contexts/shopper.ts, src/contexts/tracker.ts, src/handlers/search/searchCategoryClick.ts, src/handlers/search/searchProductClick.ts, src/handlers/search/searchRequestSent.ts, src/handlers/search/searchResponseReceived.ts, src/handlers/search/searchResultsView.ts, src/handlers/search/searchSuggestionClick.ts, src/index.ts, src/schemas.ts, src/snowplow.ts, tsconfig.json
Creates the shopper context from the Magento Storefront Events SDK data, and included it in global contexts.
[SEARCH-1163](https://jira.corp.magento.com/browse/SEARCH-1163)
We need to support the same global contexts as our existing tracker.
Locally with the `example` directory, monitoring events with the Snowplow Chrome extension and Kibana.
-   [ ] I have updated the …
=> SEARCH-1163 | create shopper context

example/index.html, src/contexts/extension.ts, src/contexts/index.ts, src/schemas.ts, src/snowplow.ts
Create the `magentoExtension` context and include it in the array of global contexts.
[SEARCH-1162](https://jira.corp.magento.com/browse/SEARCH-1162)
We need to align the global contexts with the old tracker.
Tested locally with the `example` directory, monitoring events with the Snowplow Chrome extension and Kibana.
- …
=> SEARCH-1162 | create magento extension context

src/contexts/extension.ts, src/contexts/index.ts, src/contexts/product.ts, src/contexts/search/searchInput.ts, src/contexts/search/searchResultCategory.ts, src/contexts/search/searchResultProduct.ts, src/contexts/search/searchResultSuggestion.ts, src/contexts/search/searchResults.ts, src/contexts/shopper.ts, src/contexts/shoppingCart.ts, src/contexts/storefront.ts, src/contexts/tracker.ts, src/handlers/addToCart.ts, src/handlers/placeOrder.ts, src/handlers/productView.ts, src/handlers/recommendations/recsRequestSent.ts, src/handlers/search/searchResultsView.ts, src/handlers/shoppingCartView.ts, src/snowplow.ts, src/types/contexts.d.ts
Add type definitions for all contexts and apply them to the context creators.
N/A
Doing our best to keep everything fully typed from the SDK to the collector to the Snowplow schemas.
Tested locally with the `example` directory, monitoring events through the Snowplow Chrome extension and in Kibana.
-   [x] I have read the …
=> chore: add type definitions to contexts

src/contexts/search/searchInput.ts, src/contexts/search/searchResults.ts, tests/utils/mocks/dataLayer.ts
Include `searchRequestId` in the Snowplow context.
[SEARCH-1374](https://jira.corp.magento.com/browse/SEARCH-1374)
Required to link requests and responses together in data modeling. …
=> SEARCH-1374 | search request id

example/index.html, src/events.ts, src/handlers/checkout/index.ts, src/handlers/checkout/instantPurchase.ts, tests/contexts/global.test.ts, tests/handlers/checkout/instantPurchase.test.ts
Add the `InstantPurchase` event handler.
[SEARCH-1413](https://jira.corp.magento.com/browse/SEARCH-1413)
The `SDK` has the ability to publish the `InstantPurchase` event, but the collector did not have an associated handler.
Tested with `jest` as well as the `example` directory while monitoring Snowplow events in Kibana.
- …
=> SEARCH-1413 | instant purchase event handler

src/contexts/shoppingCart.ts, src/events.ts, src/handlers/checkout/instantPurchase.ts, src/handlers/product/addToCart.ts, src/handlers/product/view.ts, src/handlers/shoppingCart/view.ts
Return `null` if the `ShoppingCart` context does not yet exist.
[SEARCH-1382](https://jira.corp.magento.com/browse/SEARCH-1382)
A customer may not have created a `ShoppingCart` yet, so the context creator should handle the case where it doesn't exist.
Tested locally with `jest`, and with the `example` directory while monitoring Snowplow events in Kibana.
-   [ ] I have …
=> SEARCH-1382 | handle empty shopping cart

src/handlers/checkout/placeOrder.ts, src/handlers/shoppingCart/view.ts, tests/handlers/checkout/placeOrder.test.ts, tests/handlers/shoppingCart/shoppingCartView.test.ts, webpack.common.js
SEARCH-1418
Remove `cartId` from the Snowplow event `value`.
[SEARCH-1418](https://jira.corp.magento.com/browse/SEARCH-1418)
The `value` field is intended to be a `number`, but our `cartId` is a `string`. This resulted in us sending `NaN` to Snowplow. In order to reconcile, we are removing `cartId` from the `value` field. This has no impact, as it's already included in the context data, and not used for modeling.
Tested locally with `jest`, as well as with the `example` directory while watching Snowplow events in Kibana.
-   [x] I have signed the [Adobe Open Source …
=> fix: remove invalid data type from value field

src/contexts/tracker.ts, src/schemas.ts, src/types/contexts.d.ts, tests/utils/mocks/context.ts
Removing the `magentoJsBuild` field from the `Tracker` context.
[SEARCH-1420](https://jira.corp.magento.com/browse/SEARCH-1420)
We no longer use Jenkins to build this library, and we never used the build number for modeling or reporting.
Tested locally with `jest` as well as in the `example` directory while monitoring Snowplow events in Kibana.
-   [ ] I have updated the …
=> SEARCH-1420 | remove js build version

src/contexts/extension.ts, src/contexts/product.ts, src/contexts/recommendationUnit.ts, src/contexts/recommendedItem.ts, src/contexts/searchInput.ts, src/contexts/searchResultCategory.ts, src/contexts/searchResultProduct.ts, src/contexts/searchResultSuggestion.ts, src/contexts/searchResults.ts, src/contexts/shopper.ts, src/contexts/shoppingCart.ts, src/contexts/storefront.ts, src/contexts/tracker.ts, src/schemas.ts, src/types/contexts.d.ts, tests/utils/mocks/context.ts
SEARCH-1421
Resolved type mismatches with `cartId` and `cartItemId`.
[SEARCH-1421](https://jira.corp.magento.com/browse/SEARCH-1421)
Snowplow schema expects `string` for `cartId` and `cartItemId` and we were passing `number`.
Tested locally with `jest` and the `example` directory while watching Snowplow Kibana for events. …
=> fix: resolve id type mismatches

package-lock.json, package.json, src/contexts/searchInput.ts, src/contexts/searchResultCategory.ts, src/contexts/searchResultProduct.ts, src/contexts/searchResultSuggestion.ts, src/contexts/searchResults.ts, src/handlers/search/searchCategoryClick.ts, src/handlers/search/searchProductClick.ts, src/handlers/search/searchRequestSent.ts, src/handlers/search/searchResponseReceived.ts, src/handlers/search/searchResultsView.ts, src/handlers/search/searchSuggestionClick.ts, src/schemas.ts, src/types/contexts.d.ts, src/utils/search.ts, tests/contexts/searchInput.test.ts, tests/contexts/searchResultCategory.test.ts, tests/contexts/searchResultProduct.test.ts, tests/contexts/searchResults.test.ts, tests/contexts/searchResultsSuggestion.test.ts, tests/search.test.ts, tests/utils/mocks/context.ts, tests/utils/mocks/dataLayer.ts
SEARCH-1474
Support multiple search bars.
[SEARCH-1474](https://jira.corp.magento.com/browse/SEARCH-1474)
There are a few places in the Magento storefront where there is more than one search bar on a page. Our data layer takes that into account, and so our collector needs to as well.
Tested with `jest` and the `example` directory while monitoring Snowplow Kibana for events.
- …
=> feat: support multiple search units

example/index.html, example/index.js, package-lock.json, src/contexts/global.ts, src/snowplow.ts, tests/contexts/global.test.ts
BREAKING CHANGE: TrackPageView is no longer called for you. You must execute this manually.
Remove the `trackPageView` when the collector is initialized. Create global contexts on demand.
N/A
This helps integrators not worry so much about what order they initialize the collector and populate the contexts.
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] My change requires a change to …
=> fix: dynamically create all global contexts and remove track page view

src/contexts/shoppingCart.ts, src/handlers/checkout/placeOrder.ts, tests/handlers/checkout/placeOrder.test.ts
Removing duplicate early `return` statement.
N/A
Just a little code cleanup!
Tested with `jest`!
-   [x] All new and existing tests passed.
=> fix: remove unnecessary early return

package-lock.json, src/contexts/recommendedItem.ts, src/contexts/shoppingCart.ts, src/handlers/search/searchCategoryClick.ts, src/handlers/search/searchProductClick.ts, src/handlers/search/searchRequestSent.ts, src/handlers/search/searchResponseReceived.ts, src/handlers/search/searchResultsView.ts, src/handlers/search/searchSuggestionClick.ts, tests/handlers/search/categoryClick.test.ts, tests/handlers/search/productClick.test.ts, tests/handlers/search/requestSent.test.ts, tests/handlers/search/responseReceived.test.ts, tests/handlers/search/resultsView.test.ts, tests/handlers/search/suggestionClick.test.ts, tests/utils/mocks/dataLayer.ts
Remove `SearchInput` context from a few events. Support `possibleOnepageCheckout`.
[DATA-3096](https://jira.corp.magento.com/browse/DATA-3096)
Prevents search input from being mismatched with the results. Maintains data parity with the legacy collector.
Tested with `jest` and the `example` directory while watching Snowplow events in Kibana.
-   [ ] I have updated the …
=> fix: remove search input context from events

src/contexts/recommendationUnit.ts, src/types/contexts.d.ts, tests/utils/mocks/context.ts
Send `placement` to Snowplow, not `pagePlacement`.
N/A
To prevent invalid contexts from being sent to Snowplow.
-   [x] I have added tests to cover my changes.
-   [x] All new and …
=> fix: fix page placement bug

src/types/contexts.d.ts
Make `price` and `currencyCode` optional.
[DATA-3400](https://jira.corp.magento.com/browse/DATA-3400)
Enables customer group pricing for B2B.
Ran existing `jest` tests.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [X] All new and existing tests passed.
=> fix: make price optional to support b2b

src/schemas.ts
Point to the latest `search-results` Snowplow schema.
[SEARCH-1686](https://jira.corp.magento.com/browse/SEARCH-1686)
Makes the `price` property in the `search-results` schema optional.
Tested locally in my Magento environment.
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] I have added tests to cover my …
=> fix: make the search results price optional

package-lock.json, package.json, src/contexts/searchResults.ts, src/schemas.ts, src/types/contexts.d.ts, tests/utils/mocks/context.ts, tests/utils/mocks/dataLayer.ts, webpack.dev.js
Add an optional `executionTime` field to the `SearchResults` context.
[SEARCH-1696](https://jira.corp.magento.com/browse/SEARCH-1696)
Supports performance tracking of our Search API.
Locally with `jest`.
-   [X] I have added tests to cover my changes.
-   [X] All new and …
=> SEARCH-1696 | Capture api-execution-time in search adaptor
