adobe/magento-storefront-event-collector

- example/index.html
- package-lock.json
- package.json
- src/events.ts
- src/index.ts
Initialize the Adobe Client Data Layer.
SEARCH-1107
The ACDL is required when working with the Magento Storefront Events SDK.
Using the `example` directory.
-   [ ] All new and existing tests passed.
> feat: initialize adobe client data layer

- example/index.html
- package-lock.json
- package.json
- src/contexts/index.ts
- src/contexts/storefrontInstance.ts
- src/schemas.ts
- src/snowplow.ts
Create the `StorefrontInstance` context and include it in the array of global contexts.
[SEARCH-1160](https://jira.corp.magento.com/browse/SEARCH-1160)
We need to support all global contexts from our existing tracker.
Tested locally with the `example` directory, and monitoring events with the Snowplow Chrome extension and Kibana.
-   [ ] I have updated the documentation …
> SEARCH-1160 | create storefront instance context

- example/index.html
- package-lock.json
- package.json
- src/contexts/index.ts
- src/contexts/shoppingCart.ts
- src/schemas.ts
- src/snowplow.ts
Create the `shoppingCart` context and include it in the array of global contexts.
[SEARCH-1164](https://jira.corp.magento.com/browse/SEARCH-1164)
We need to align the global contexts with the old tracker.
Tested locally with the `example` directory, monitoring events with the Snowplow Chrome extension and Kibana.
-   [X] I …
> SEARCH-1164 | create shopping cart context

- .eslintrc
- package-lock.json
- package.json
- src/contexts/extension.ts
- src/contexts/index.ts
- src/contexts/search/searchInput.ts
- src/contexts/search/searchResultCategory.ts
- src/contexts/search/searchResultProduct.ts
- src/contexts/search/searchResultSuggestion.ts
- src/contexts/search/searchResults.ts
- src/contexts/shopper.ts
- src/contexts/shoppingCart.ts
- src/contexts/storefrontInstance.ts
- src/contexts/tracker.ts
- src/events.ts
- src/index.ts
Automatically sort imports and exports.
N/A
Bring eslint rules in line with other Magento frontend repositories.
Manually.
-   [X] All new and existing tests passed.
> chore: add import sorting to eslint rules

- .eslintrc
- example/index.html
- package-lock.json
- package.json
- src/contexts/extension.ts
- src/contexts/index.ts
- src/contexts/product.ts
- src/contexts/search/searchInput.ts
- src/contexts/search/searchResultCategory.ts
- src/contexts/search/searchResultProduct.ts
- src/contexts/search/searchResultSuggestion.ts
- src/contexts/search/searchResults.ts
- src/contexts/shopper.ts
- src/contexts/shoppingCart.ts
- src/contexts/storefrontInstance.ts
- src/contexts/tracker.ts
- src/events.ts
- src/handlers/addToCart.ts
- src/handlers/index.ts
- src/index.ts
- src/schemas.ts
Implement the product `add-to-cart` event.
[SEARCH-1154](https://jira.corp.magento.com/browse/SEARCH-1154)
This event is needed to calculate conversation rates for Product Recommendations and Search.
Locally with the `example` directory. Monitored Snowplow events with the Chrome extension and through Kibana.
-   [x] I have …
> SEARCH-1154 | support product add to cart event

- .eslintrc
- example/index.html
- package-lock.json
- package.json
- src/contexts/extension.ts
- src/contexts/index.ts
- src/contexts/product.ts
- src/contexts/search/searchInput.ts
- src/contexts/search/searchResultCategory.ts
- src/contexts/search/searchResultProduct.ts
- src/contexts/search/searchResultSuggestion.ts
- src/contexts/search/searchResults.ts
- src/contexts/shopper.ts
- src/contexts/shoppingCart.ts
- src/contexts/storefrontInstance.ts
- src/contexts/tracker.ts
- src/events.ts
- src/handlers/addToCart.ts
- src/handlers/index.ts
- src/handlers/placeOrder.ts
- src/index.ts
- src/schemas.ts
Implement the `place-order` event.
[SEARCH-1156](https://jira.corp.magento.com/browse/SEARCH-1156)
Need to track `place-order` events in order to improve Product Recommendations and Search results.
Locally with the `example` directory. Monitored Snowplow events with the Chrome extension and in Kibana.
-   [x] I have read …
> SEARCH-1156 | support place order event

- example/index.html
- src/events.ts
- src/handlers/index.ts
- src/handlers/productView.ts
Implement the `product-view` event.
[SEARCH-1153](https://jira.corp.magento.com/browse/SEARCH-1153)
This event is required to improve Product Recommendations and Search results.
Locally with the `example` directory, monitoring Snowplow events with the Chrome extension and in Kibana.
-   [x] I have read the **CONTRIBUTING** …
> SEARCH-1153 | support product view event

- example/index.html
- src/events.ts
- src/handlers/index.ts
- src/handlers/recommendations/index.ts
- src/handlers/recommendations/recsRequestSent.ts
Implement the `recommendation-api-response-received` event.
[SEARCH-1274](https://jira.corp.magento.com/browse/SEARCH-1274)
This is needed to improve Product Recommendations and Search results.
Locally with the `example` directory while monitoring Snowplow events with the Chrome extension and in Kibana.
-   [x] I have read …
> SEARCH-1274 | support recommendation api response received event

- package-lock.json
- package.json
- src/contexts/search/searchInput.ts
- src/contexts/search/searchResults.ts
- src/schemas.ts
- src/types/contexts.d.ts
- src/utils/search.ts
- tests/search.test.ts
- tests/utils/mocks/context.ts
- tests/utils/mocks/dataLayer.ts
Update the `SearchInput` and `SearchResults` schemas to the latest version.
[SEARCH-1342](https://jira.corp.magento.com/browse/SEARCH-1342)
Necessary to support required fields in data modeling.
-   [x] I have read the …
> SEARCH-1342 | update schema versions

- package-lock.json
- package.json
- src/contexts/product.ts
- src/contexts/shoppingCart.ts
- src/snowplow.ts
Enable link click tracking events.
[SEARCH-1392](https://jira.corp.magento.com/browse/SEARCH-1392)
To be in parity with our legacy collector, we need to implement link click tracking.
Tested with the `example` directory while monitoring Snowplow events in Kibana.
-   [ ] I …
> SEARCH-1392 | link click tracking

- example/index.html
- package-lock.json
- package.json
- src/events.ts
- src/handlers/index.ts
- src/handlers/page/index.ts
- src/handlers/page/view.ts
- tests/handlers/page/view.test.ts
SEARCH-1410
Add an event handler for the `PageView` event.
[SEARCH-1410](https://jira.corp.magento.com/browse/SEARCH-1410)
Although the `Magento Storefront Events SDK` supported publishing the `PageView` event, the collector never offered a handler for it.
Tested with `jest`, as well as with the `example` directory while monitoring Snowplow events in Kibana.
-   [ ] I have …
> feat: add page view event handler

- package-lock.json
- package.json
Update the `Magento Storefront Events SDK` to the latest version.
N/A
Third party integrators will want the flexibility to create their own custom contexts without having to use the `Adobe Client Data Layer` directly, so we exposed the `getContext` and `setContext` methods.
Tested locally with `jest`.
-   [x] I have read …
> chore: update storefront sdk

- example/index.html
- package-lock.json
- package.json
- src/contexts/recommendedItem.ts
- src/contexts/searchInput.ts
- src/contexts/shoppingCart.ts
- src/handlers/checkout/instantPurchase.ts
- src/handlers/product/addToCart.ts
- src/handlers/product/view.ts
- src/handlers/recommendations/recsItemAddToCartClick.ts
- src/handlers/recommendations/recsItemClick.ts
- src/schemas.ts
- src/types/contexts.d.ts
- src/utils/search.ts
- tests/search.test.ts
- tests/utils/mocks/context.ts
- tests/utils/mocks/dataLayer.ts
Support the new `SearchInput` context structure.
N/A
Required to support the latest Snowplow schemas.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing …
> support new SearchInput schemas

- .github/workflows/merge-to-main.yml
-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] All new and existing tests passed.
> Search 1471

- package.json
- webpack.dev.js
Use different Snowplow collector URLs for each environment.
N/A
Now that we're hosting a QA build, we need to ensure it's pointing to the right collector endpoint.
Tested locally with the `example` directory.
-   [x] All new …
> chore: update snowplow collector urls

- package-lock.json
- src/contexts/product.ts
- src/types/contexts.d.ts
- src/utils/product.ts
Make the `product.pricing` property optional.
N/A
In some cases, the storefront might not have this information, so we've made it optional.
-   [ ] I have added tests to cover my …
> fix: make product pricing optional

- README.md
Added a proper `README`.
[SEARCH-1334](https://jira.corp.magento.com/browse/SEARCH-1334)
Until we have full `DevDocs` integration, the `README` will serve as the main source of documentation.
N/A
-   [x] My change requires a change to the documentation.
-   [x] I have updated the documentation accordingly.
-   [x] All new and existing …
> SEARCH-1334 | improve readme

- package-lock.json
- package.json
- src/contexts/recommendationUnit.ts
- src/snowplow.ts
- tests/utils/mocks/context.ts
- tests/utils/mocks/dataLayer.ts
- webpack.prod.js
Support the `placement` and `offset` values in the `RecommendationUnit` context.
N/A
We want to maintain parity with the data gathered from the legacy collector.
-   [x] I have added …
> feat: populate placement and offset values

- package-lock.json
- package.json
- src/contexts/shoppingCart.ts
- src/types/contexts.d.ts
- tests/utils/mocks/context.ts
- tests/utils/mocks/dataLayer.ts
Support the `giftMessageSelected` and `giftWrappingSelected` fields.
N/A
Maintain parity with the legacy collector.
-   [x] I have added tests to cover my changes.
-   [x] All new …
> feat: support gift options

- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Add source maps to the development build.
N/A
Helps us debug!
Tested with `jest`.
-   [x] All new and existing tests passed.
> build: include source maps in dev build

- webpack.qa.js
-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] All new and existing tests passed.
> build: actually add source maps to qa build

- package-lock.json
- package.json
Update the Magento Storefront Events SDK to `v1.0.0`.
N/A
Release party 🎉
Tested with `jest` and the `example` directory.
-   [x] All new and existing tests passed.
> chore: update magento storefront events sdk

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 1.1.2

- README.md
- src/aep/types/alloy.types.ts
- src/alloy.ts
-   [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] I have read the **CONTRIBUTING** document.
-   [ ] All new and existing tests passed.
> DINT-246: Configure alloy with cookie restrictions.
